// Code generated by "stringer -type=BoundType --output=bound_string.go"; DO NOT EDIT.

package ranger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INCLUSIVE-0]
	_ = x[EXCLUSIVE-1]
	_ = x[OPEN-2]
}

const _BoundType_name = "INCLUSIVEEXCLUSIVEOPEN"

var _BoundType_index = [...]uint8{0, 9, 18, 22}

func (i BoundType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BoundType_index)-1 {
		return "BoundType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BoundType_name[_BoundType_index[idx]:_BoundType_index[idx+1]]
}
